### ISSUE TITLE
RuntimeError: Invalid device string: 'cuda:None'

### ISSUE THREAD

**Issue by ruanling** [heurist-network/miner-release#56] opened 2024-07-26 15:09 UTC
![image](https://github.com/user-attachments/assets/7f922e96-ce5b-4781-9308-fc75624c9f95)

In requirements.txt, I installed torch==2.1.0 and got an error, so I upgraded to version 2.3.0. I installed CUDA version 121.
After installing and running the command sd-miner-v1.3.1.py, it gives the following error.
The versions in requirements.txt do not match the current ones, so the error occurs.

**Comment by wjw12** [comment] 2024-07-29 03:18
@ruanling The issue is fixed in the latest version. Sorry for the inconvenience.

**Closed by wjw12** 2024-07-29 03:18 UTC
